### ISSUE TITLE
Add loops to marker files

### ISSUE THREAD

**Issue by sascha-andres** [monobuild/monobuild#6]
**Is your feature request related to a problem?**

I have a build that must be run multiple times with different inputs. A loop calling the commands for each possible input would help me

**Describe the solution you'd like**

```
---

commands:
  - echo {%= .Item =%}
  - echo ${test}
environment:
  test: {%= .Item =%}
label: main
loops:
  values:
    - DE
    - FR
```

**Describe alternatives you've considered**

Using external tools to run a loop and passing values over to them
